name: workflow2
on: [workflow_dispatch]
jobs:
    testjob:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3

            - name: Install Nodejs
              uses: actions/setup-node@v3


            - name: Install dependencies
              run: |
                cd project
                npm ci

            - name: Run Tests
              run: |
                cd project
                npm test


    build-and-deploy:
        needs: [testjob]
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3

            - name: Install Nodejs
              uses: actions/setup-node@v3


            - name: Install dependencies
              run: |
                cd project
                npm ci
 
            - name: Build project
              run: |
                cd project
                npm run build

            - name: Deploying
              run: echo "Deploying....."
        
