name: 'Manual Cloud Function Deploy'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (dev or prod)'
        required: true
        type: choice
        options:
          - dev
          - prod
env:
  ENVIRONMENT: ${{ github.event.inputs.environment }}

jobs:
  deploy-cloud-function:
    name: 'Deploy Cloud Function'
    runs-on: ubuntu-24.04
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Set environment variable
        run: echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      # Run the script to create Cloud functions
      - name: 'Run Cloud Func Script'
        run: |   
           cd testerkk
           python abc.py
